global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'dotnet'
    static_configs:
      - targets: ['dotnet-service:80']

  - job_name: 'python'
    static_configs:
      - targets: ['python-service:8000']
